CREATE TABLE member(
	num INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(10) NOT NULL,
	id VARCHAR(15) NOT NULL,
	pw VARCHAR(30) NOT NULL,
	email VARCHAR(80) NOT NULL,
	phone VARCHAR(13) NOT NULL,
	level INT DEFAULT 9,
	point INT DEFAULT 0,
	PRIMARY KEY (num)
) CHARSET = UTF8MB4;